server:
  port: 10003

spring:
  application:
    name: cloud-client

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10001/eureka/