server:
  port: 10002

spring:
  application:
    name: cloud-gateway

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10001/eureka/
