server:
  port: 10002

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启服务的自动注册发现（及以注册中心的服务ID自动配置路由）
          lower-case-service-id: true #服务ID小写

      default-filters:
        - Elapsed=true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10001/eureka/

logging:
  level:
    root: info
  file: logs/gateway.log

