server:
  #特地和gateway使用同一个端口，防止重复启动
  port: 10002

spring:
  application:
    name: cloud-zuul

  servlet:
    #上传文件的配置，网关必须配置
    multipart:
      max-file-size: 50MB
      max-request-size: 10MB

  redis:
    host: localhost
    port: 6379
    database: 0

#这是zuul基于注册中心动态发现服务路由配置
#这个默认就是开启的
ribbon:
  eureka:
    enabled: true
  #这个是重试和超时时间
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 0
  ConnectTimeout: 500
  ReadTimeout: 5000


#静态路由配置(服务ID不分大小写)
zuul:
  host:
    connect-timeout-millis: 8000
    socket-timeout-millis: 6000
  retryable: true

  routes:
    cloud-client-1:
      path: /cloud-client-1/**
      serviceId: cloud-client

  ratelimit:
    #开启限流
    enabled: true
    #限流内容存储介质
    repository: redis
    #全局限流
    default-policy-list:
      #这个配置是每10秒只能请求10次，且时间长度不能大于1秒
      - limit: 10
        quota: 10
        refresh-interval: 10
        #限流类型（user,origin,url）
        type:
          - url
    policy-list:
      #单个应用(下面这个配置需要和serviceId相同或者与配置的路由前缀相同，测试的时候要和全局分开)
      cloud-client-1:
        - limit: 1
          quota: 1
          refresh-interval: 3


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10000/eureka/

logging:
  level:
    root: info
  file: logs/zuul.log

