server:
  port: 10004

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #git仓库地址
          uri: https://github.com/a604364157/other
          #仓库下相对地址
          search-paths: config-repo
#          username:
#          password:


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10001/eureka/
