server:
  port: 10004

spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          #git仓库地址
          uri: https://github.com/a604364157/other
          #仓库下相对地址
          search-paths: config-repo
#          username:
#          password:

    #消息总线配置
    bus:
      enabled: true
      trace:
        enabled: true
  #mq的配置，默认配置，不配也是这个
  rabbitmq:
    host: localhost
    port: 5672

#开启自动刷新，消息总线方式，这是开在服务端
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10001/eureka/
